data_configs:
  data_path: '/mnt/SSD6/nathan/desnow/data/'
  norm_by_image: True
  sample_shape: 64

  # if set to 1, it will not use multiprocessing
  dataset_workers: 1 # currently no using multiprocessing since it creates a bottleneck
  from_tensor: False
  # This is a temporary resize to 299x299 since I don't have time to mess with Inception-v4's architecture
  temp_resize: True
  # for developing with less than the full dataset to save time
  num_images: 100

training_configs:
  batch_size: 5
  num_workers: 2
# sets kernel sizes to range over 2^i, i=[0,dilation_range)
# same as the number of levels in the dialation pyrimand

model_configs:
  dilation_pyramid_configs:

    # make sure this is such that the output dimensions don't change
    conv_configs:
      out_channels: 1536
      # padding only accomodates odd kernel size
      kernel_size: 3
      stride: 1
      bias: False
    # gamma in the paper
    levels: 3

  trans_recovery_configs:
    snow_mask_configs:
      conv_configs:
        stride: 1
        bias: False
      kernel_levels: 4
    abberation_configs:
      conv_configs:
        stride: 1
        bias: False
      kernel_levels: 4
    decoder_configs:
      conv_configs:
        stride: 2
        kernel_size: 5

  # beta in the paper
  rg_dilation_levels: 4